### ISSUE TITLE
Unable to create nominations during election

### ISSUE THREAD

**Issue by treed593** [agileware/au.com.agileware.elections#6]
CMS: Wordpress 5.9
CiviCRM Version: 5.45.2
Elections Version: 1.2.2

Wordpress and CiviCRM are running in a Docker container based on Ubuntu

When viewing the "Elections Page" for my newly created election, I am seeing PHP errors:
```
Nominations for President
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 29
There are no existing nominations

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 94
Nominations for 1st Vice-President
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 29
There are no existing nominations

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 94
Nominations for 2nd Vice-President
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 29
There are no existing nominations

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 94
Nominations for Secretary
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 29
There are no existing nominations

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 94
Nominations for Treasurer
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 29
There are no existing nominations

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 94
Nominations for Board Member
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 29
There are no existing nominations

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/uploads/civicrm/templates_c/en_US/%%63/633/6330B7D7%%nominations.tpl.php on line 94
```

And when trying to submit a nomination, I get the following:
![image](https://user-images.githubusercontent.com/6807466/151821235-e2fe3920-94fa-40c4-9743-da1a298ad998.png)
```
CiviCRM_API3_Exception: "Nomination cannot be added for deleted election."

#0 /var/www/html/wp-content/uploads/civicrm/ext/au.com.agileware.elections/CRM/Elections/Form/CreateElectionNomination.php(151): civicrm_api3("ElectionNomination", "create", (Array:3))
#1 /var/www/html/wp-content/uploads/civicrm/ext/au.com.agileware.elections/CRM/Elections/Form/CreateElectionNomination.php(166): CRM_Elections_Form_CreateElectionNomination->getNominationId((Array:8))
#2 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(565): CRM_Elections_Form_CreateElectionNomination->postProcess()
#3 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Submit.php(56): CRM_Core_Form->mainProcess()
#4 /var/www/html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Submit->perform(Object(CRM_Elections_Form_CreateElectionNomination), "submit")
#5 /var/www/html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Elections_Form_CreateElectionNomination), "submit")
#6 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle("submit")
#7 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php(98): CRM_Core_Controller->run()
#8 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(292): CRM_Utils_Wrapper->run("CRM_Elections_Form_CreateElectionNomination", "Create Election Nomination", (Array:0))
#9 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem((Array:13))
#10 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke((Array:4))
#11 /var/www/html/wp-content/plugins/civicrm/civicrm.php(1169): CRM_Core_Invoke::invoke((Array:4))
#12 /var/www/html/wp-includes/class-wp-hook.php(307): CiviCRM_For_WordPress->invoke("")
#13 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters("", (Array:1))
#14 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action((Array:1))
#15 /var/www/html/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#16 {main}
 Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
Nomination cannot be added for deleted election.
Return to home page.
```

**Comment by treed593** [comment]
Apparently, I didn't see the "Election is Inactive" flag that needed to be set to true, setting that to True allowed the nomination, but these errors may still need to be handled.

**Comment by agileware-justin** [comment]
PHP warnings, not errors. What PHP version are you using?
